#if UNITY_ANDROID
using System.IO;
using System.Xml.Linq;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

namespace SplenSoft.Unity.Editor
{
    /// <summary>
    /// Post-processes the Android Gradle project generated by Unity to add the
    /// permissions and service declaration required by
    /// <see cref="BackgroundTaskManager"/>:
    /// <list type="bullet">
    ///   <item><description>
    ///     Adds <c>FOREGROUND_SERVICE</c> and
    ///     <c>FOREGROUND_SERVICE_DATA_SYNC</c> (API 34+) permissions.
    ///   </description></item>
    ///   <item><description>
    ///     Declares <c>NetworkQueueForegroundService</c> with
    ///     <c>foregroundServiceType="dataSync"</c>.
    ///   </description></item>
    /// </list>
    /// The post-processor edits (or creates) the
    /// <c>AndroidManifest.xml</c> file in the Gradle project's
    /// <c>src/main</c> directory.
    /// </summary>
    public static class AndroidBuildPostProcessor
    {
        private const string ServiceClass =
            "com.splensoft.webapiservice.NetworkQueueForegroundService";

        private const string AndroidNS =
            "http://schemas.android.com/apk/res/android";

        [PostProcessBuild(100)]
        public static void OnPostProcessBuild(
            BuildTarget target, string buildPath)
        {
            if (target != BuildTarget.Android)
                return;

            Debug.Log(
                "[AndroidBuildPostProcessor] Configuring AndroidManifest.xml " +
                "for background foreground-service support.");

            string manifestPath = FindManifestPath(buildPath);

            if (manifestPath == null)
            {
                Debug.LogWarning(
                    "[AndroidBuildPostProcessor] Could not locate " +
                    "AndroidManifest.xml.  Skipping manifest modification.");
                return;
            }

            ModifyManifest(manifestPath);
        }

        // ── Path discovery ────────────────────────────────────────────────────

        private static string FindManifestPath(string buildPath)
        {
            // Gradle export layout: <buildPath>/unityLibrary/src/main/AndroidManifest.xml
            // or (older): <buildPath>/src/main/AndroidManifest.xml
            string[] candidates =
            {
                Path.Combine(buildPath, "unityLibrary", "src", "main",
                    "AndroidManifest.xml"),
                Path.Combine(buildPath, "launcher", "src", "main",
                    "AndroidManifest.xml"),
                Path.Combine(buildPath, "src", "main",
                    "AndroidManifest.xml"),
                // APK build (non-exported): buildPath is the .apk file's
                // parent; look for the manifest beside it.
                Path.Combine(buildPath, "AndroidManifest.xml"),
            };

            foreach (string path in candidates)
            {
                if (File.Exists(path))
                    return path;
            }
            return null;
        }

        // ── Manifest editing ──────────────────────────────────────────────────

        private static void ModifyManifest(string manifestPath)
        {
            XDocument doc = XDocument.Load(manifestPath);
            XElement manifest = doc.Root;

            if (manifest == null)
            {
                Debug.LogError(
                    "[AndroidBuildPostProcessor] Invalid AndroidManifest.xml " +
                    "(root element is null).");
                return;
            }

            XNamespace ns = AndroidNS;

            // ── Permissions ───────────────────────────────────────────────────
            AddPermissionIfMissing(
                manifest, ns, "android.permission.FOREGROUND_SERVICE");

            // API 34 (Android 14) requires a typed foreground-service
            // permission in addition to the base one.
            AddPermissionIfMissing(
                manifest, ns,
                "android.permission.FOREGROUND_SERVICE_DATA_SYNC");

            // ── <application> element ─────────────────────────────────────────
            XElement application = manifest.Element("application");
            if (application == null)
            {
                application = new XElement("application");
                manifest.Add(application);
            }

            // ── Service declaration ───────────────────────────────────────────
            if (!ServiceAlreadyDeclared(application, ns))
            {
                var serviceElement = new XElement("service",
                    new XAttribute(ns + "name",    ServiceClass),
                    new XAttribute(ns + "enabled", "true"),
                    new XAttribute(ns + "exported","false"),
                    // Required on API 29+
                    new XAttribute(ns + "foregroundServiceType", "dataSync")
                );
                application.Add(serviceElement);

                Debug.Log(
                    "[AndroidBuildPostProcessor] Added foreground service " +
                    $"declaration for {ServiceClass}.");
            }
            else
            {
                Debug.Log(
                    "[AndroidBuildPostProcessor] Foreground service already " +
                    "declared – skipping.");
            }

            doc.Save(manifestPath);

            Debug.Log(
                "[AndroidBuildPostProcessor] AndroidManifest.xml updated at " +
                manifestPath);
        }

        private static void AddPermissionIfMissing(
            XElement manifest, XNamespace ns, string permissionName)
        {
            foreach (XElement el in manifest.Elements("uses-permission"))
            {
                string name = (string)el.Attribute(ns + "name");
                if (name == permissionName)
                    return; // already present
            }

            manifest.Add(new XElement("uses-permission",
                new XAttribute(ns + "name", permissionName)));

            Debug.Log(
                $"[AndroidBuildPostProcessor] Added permission: " +
                permissionName);
        }

        private static bool ServiceAlreadyDeclared(
            XElement application, XNamespace ns)
        {
            foreach (XElement el in application.Elements("service"))
            {
                string name = (string)el.Attribute(ns + "name");
                if (name == ServiceClass)
                    return true;
            }
            return false;
        }
    }
}
#endif
