#if UNITY_IOS
using System.IO;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEngine;

namespace SplenSoft.Unity.Editor
{
    /// <summary>
    /// Post-processes the Xcode project generated by Unity to enable the iOS
    /// Background Modes required by <see cref="BackgroundTaskManager"/>:
    /// <list type="bullet">
    ///   <item><description>
    ///     Adds <c>fetch</c> and <c>processing</c> to
    ///     <c>UIBackgroundModes</c> in <c>Info.plist</c>.
    ///   </description></item>
    ///   <item><description>
    ///     Adds the BGProcessingTask identifier to
    ///     <c>BGTaskSchedulerPermittedIdentifiers</c> in
    ///     <c>Info.plist</c>.
    ///   </description></item>
    ///   <item><description>
    ///     Links the <c>BackgroundTasks.framework</c> (weak-links so the app
    ///     still runs on iOS 12 without a crash).
    ///   </description></item>
    ///   <item><description>
    ///     Enables the Background Modes capability in the Xcode project.
    ///   </description></item>
    /// </list>
    /// </summary>
    public static class iOSBuildPostProcessor
    {
        // Must match BackgroundTaskManager.IOSBGTaskIdentifier default value
        // and Info.plist BGTaskSchedulerPermittedIdentifiers entry.
        private const string BGTaskIdentifier =
            "com.splensoft.webapiservice.networkqueue";

        [PostProcessBuild(100)]
        public static void OnPostProcessBuild(BuildTarget target, string buildPath)
        {
            if (target != BuildTarget.iOS)
                return;

            Debug.Log("[iOSBuildPostProcessor] Configuring Xcode project for " +
                      "background networking support.");

            ModifyInfoPlist(buildPath);
            ModifyXcodeProject(buildPath);
        }

        // ── Info.plist ────────────────────────────────────────────────────────

        private static void ModifyInfoPlist(string buildPath)
        {
            string plistPath = Path.Combine(buildPath, "Info.plist");
            var plist = new PlistDocument();
            plist.ReadFromFile(plistPath);

            PlistElementDict rootDict = plist.root;

            // ── UIBackgroundModes ─────────────────────────────────────────────
            const string uiBGModesKey = "UIBackgroundModes";

            if (!rootDict.values.ContainsKey(uiBGModesKey))
                rootDict.CreateArray(uiBGModesKey);

            var bgModes = rootDict[uiBGModesKey].AsArray();

            AddStringIfMissing(bgModes, "fetch");
            AddStringIfMissing(bgModes, "processing");

            // ── BGTaskSchedulerPermittedIdentifiers ───────────────────────────
            const string bgTaskKey = "BGTaskSchedulerPermittedIdentifiers";

            if (!rootDict.values.ContainsKey(bgTaskKey))
                rootDict.CreateArray(bgTaskKey);

            var bgTaskIds = rootDict[bgTaskKey].AsArray();
            AddStringIfMissing(bgTaskIds, BGTaskIdentifier);

            plist.WriteToFile(plistPath);

            Debug.Log("[iOSBuildPostProcessor] Info.plist updated with " +
                      "background modes and BGTaskScheduler identifier.");
        }

        private static void AddStringIfMissing(
            PlistElementArray array, string value)
        {
            foreach (var element in array.values)
            {
                if (element is PlistElementString s &&
                    s.value == value)
                    return;
            }
            array.AddString(value);
        }

        // ── Xcode project ─────────────────────────────────────────────────────

        private static void ModifyXcodeProject(string buildPath)
        {
            string projPath = PBXProject.GetPBXProjectPath(buildPath);
            var proj = new PBXProject();
            proj.ReadFromFile(projPath);

            string mainTargetGuid = proj.GetUnityMainTargetGuid();
            string frameworkTargetGuid =
                proj.GetUnityFrameworkTargetGuid();

            // ── Link BackgroundTasks.framework (weak, iOS 13+) ────────────────
            // Weak-linking means the app launches on iOS < 13 and the
            // BackgroundTasks APIs are simply unavailable (guarded with
            // @available checks in the native plugin).
            proj.AddFrameworkToProject(
                mainTargetGuid,
                "BackgroundTasks.framework",
                weak: true);

            proj.AddFrameworkToProject(
                frameworkTargetGuid,
                "BackgroundTasks.framework",
                weak: true);

            // ── Background Modes capability ───────────────────────────────────
            // Writes the necessary entitlements and enables the capability so
            // Xcode doesn't strip it during signing.
            proj.AddCapability(
                mainTargetGuid,
                PBXCapabilityType.BackgroundModes);

            proj.WriteToFile(projPath);

            // ── Entitlements (.entitlements) ──────────────────────────────────
            // Unity 2019.3+ generates an entitlements file automatically when a
            // capability is added; ensure the background-task key is present.
            string entitlementsFileName =
                proj.GetBuildPropertyForAnyConfig(
                    mainTargetGuid,
                    "CODE_SIGN_ENTITLEMENTS");

            if (!string.IsNullOrEmpty(entitlementsFileName))
            {
                string entitlementsPath =
                    Path.Combine(buildPath, entitlementsFileName);
                ModifyEntitlements(entitlementsPath);
            }

            Debug.Log("[iOSBuildPostProcessor] Xcode project updated.");
        }

        private static void ModifyEntitlements(string entitlementsPath)
        {
            if (!File.Exists(entitlementsPath))
                return;

            var plist = new PlistDocument();
            plist.ReadFromFile(entitlementsPath);

            PlistElementDict rootDict = plist.root;

            // com.apple.developer.background-task-scheduler-permitted-identifiers
            const string key =
                "com.apple.developer.background-task-scheduler-" +
                "permitted-identifiers";

            if (!rootDict.values.ContainsKey(key))
                rootDict.CreateArray(key);

            var array = rootDict[key].AsArray();
            AddStringIfMissing(array, BGTaskIdentifier);

            plist.WriteToFile(entitlementsPath);

            Debug.Log("[iOSBuildPostProcessor] Entitlements file updated with " +
                      "BGTaskScheduler identifier.");
        }
    }
}
#endif
